[package]
name = "runner"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "*"
wasmtime = "*"
wasmtime-wasi = "*"
wit-bindgen-wasmtime = { git = "https://github.com/bytecodealliance/wit-bindgen.git" }
